### ISSUE TITLE
withPopups clashes with forwardRef

### ISSUE THREAD

**Issue by uplight-dev** [wix-incubator/react-popup-manager#4]
export default forwardRef(withPopups()(MyComponent));

causes the forwardRef to use a modified version of the expected MyComponent(of type ForwardFn). This breaks the forwardRef usages and doesn't allow refS to be applied correctly.

**Comment by dev4light** [comment]
a possible workaround is to do withPopups()(ParentComponent) and pass popupManager prop to MyComponent child.
