### ISSUE TITLE
[Feature] support default global manager.

### ISSUE THREAD

**Issue by lwyj123** [wix-incubator/react-popup-manager#7]
it's convenient to have a default global manager that can simply call `open`, `closeAll` without using Provider in practice. But developer can use provider to control different part of logic in advanced use case.

```Typescript
import {open, closeAll} from 'react-popup-manager'

// ...
open(MyModal, {title: 'my modal'})
closeAll()
```
or
```Typescript
import {globalManager} from 'react-popup-manager'

// ...
globalManager.open(MyModal, {title: 'my modal'})
globalManager.closeAll()
```

**Comment by varzager** [comment]
@lwyj123 there is a solution which is close to that using [hooks](https://github.com/wix-incubator/react-popup-manager#hooks)

```Typescript
import React from "react";
import { usePopupManager } from "react-popup-manager";
import { MyModal } from './MyModal'

//...
const {open, closeAll} = usePopupManager();
```

does that help?
