### ISSUE TITLE
[Feature] Support popup id for close

### ISSUE THREAD

**Issue by lwyj123** [wix-incubator/react-popup-manager#8]
In some use cases developer may need to close only some popup. It's convenient to support API like this.

```Typescript

popupManager.open(MyModal, {id: "test"})

popupManager.close("test")
```

**Comment by varzager** [comment]
Hey @lwyj123,
`popupManager.open` returns an object containing a function called `close`.
You can use this to close that specific popup.
Does that solve your issue?
