### ISSUE TITLE
Module '"react-popup-manager"' has no exported member 'usePopupManager'

### ISSUE THREAD

**Issue by deeptha6** [wix-incubator/react-popup-manager#9]

**Comment by bggolding** [comment]
There's something really wrong here: usePopupManager is defined in ./dist/src/index.d.ts but not in ./index.d.ts. Could something be wrong in the build process?

**Comment by jamalsoueidan** [comment]
Got the same issue

**Comment by DonGissel** [comment]
Using v2.1.1, and importing like this (it was the default that Webstorm resolved for me), it worked just fine:

```
import { usePopupManager } from 'react-popup-manager/dist/src';
```

It's not exported through the default module, though, and that could be better. :)

**Comment by varzager** [comment]
I fixed it now. 
Pushed a new version `v2.1.2`. Now it is exported through the default module -
`import { usePopupManager } from 'react-popup-manager';`
